[project]
name = "go-filter-bp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rdflib>=7.5.0",
    "requests>=2.32.5",
]
